### ISSUE TITLE
**Issue: Black screen - Switch Collection ROMs**

### ISSUE THREAD

**Issue by royfokk** [libretro/nestopia#101]
**Affected No-Intro ROMs:**  
- Kid Dracula (World) (Castlevania Anniversary Collection)  
- Ninja JaJaMaru - The Ninja Skill Book (USA, Europe) (Ninja JaJaMaru Retro Collection) (Switch)  

**Problem:**  
Black screen on launch  

**Environment:**  
d2eefab298b0b9152d2934d6f0227b6803c877b3

**Comment by royfokk** [comment]
Kid Dracula (World) (Castlevania Anniversary Collection).nes
md5 cc17ba8fb8db20c53449c8a1a1bda08c
Kid Dracula (World) (Castlevania Anniversary Collection).sav
md5 dce27edb434d238613f928daa5c50632
Ninja JaJaMaru - The Ninja Skill Book (USA, Europe) (Ninja JaJaMaru Retro Collection) (Switch).nes
md5 64d1329ce8f2362bdcbff9cdc2636eb6

**Comment by carmiker** [comment]
Ninja JaJaMaru - The Ninja Skill Book should now work, complete with correct saving and enemy encounters (which do not work if you do not have SRAM hooked up properly and just emulate it using a standard JF22/VRC1).

**Comment by carmiker** [comment]
Kid Dracula (World) (Castlevania Anniversary Collection) should now work, but you do need to place the "seed" save file into the correct location, with the correct filename.

**Comment by royfokk** [comment]
Ninja JaJaMaru - The Ninja Skill Book is OK now.
Thank you very much.

But, 
I put both Kid Dracula (World) (Castlevania Anniversary Collection).nes and Kid Dracula (World) (Castlevania Anniversary Collection).sav in the same folder, but it still doesn't work. 
Is there anything wrong with my operation?

**Comment by royfokk** [comment]
I have updated the NstDatabase.xml file. It still does not work.

**Comment by carmiker** [comment]
The .sav file needs to be in your save directory, which is not necessarily the same as your ROM directory.

**Comment by royfokk** [comment]
I changed the file extension from .sav to .srm and put it in the save folder. It works now. Thanks!
